name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: go-averi2d.x86_64

          - goos: windows
            goarch: amd64
            cgo: 1
            cc: x86_64-w64-mingw32-gcc
            output: go-averi2d.exe

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26.5'
      - name: Install cross compiler
        run: |
            sudo apt-get update
            sudo apt-get install -y gcc-mingw-w64-x86-64
      - name: Download dependencies
        run: go mod download

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.cgo }}
          CC: ${{ matrix.cc }}
        run: |
          mkdir -p dist
          go build -ldflags "-s -w" -o dist/${{ matrix.output }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: dist/${{ matrix.output }}
